/* eslint-disable @typescript-eslint/camelcase */
export default [
  {
    added_at: "2020-02-25T20:31:38Z",
    added_by: {
      external_urls: {
        spotify: "https://open.spotify.com/user/",
      },
      href: "https://api.spotify.com/v1/users/",
      id: "",
      type: "user",
      uri: "spotify:user:",
    },
    is_local: false,
    primary_color: null,
    track: {
      album: {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/78xUyw6FkVZrRAtziFdtdu",
            },
            href: "https://api.spotify.com/v1/artists/78xUyw6FkVZrRAtziFdtdu",
            id: "78xUyw6FkVZrRAtziFdtdu",
            name: "The Roots",
            type: "artist",
            uri: "spotify:artist:78xUyw6FkVZrRAtziFdtdu",
          },
        ],
        available_markets: [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0qbl8aNaCUOvX8HGsZYLfh",
        },
        href: "https://api.spotify.com/v1/albums/0qbl8aNaCUOvX8HGsZYLfh",
        id: "0qbl8aNaCUOvX8HGsZYLfh",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b273bac8015c7e47644fb86e27e2",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e02bac8015c7e47644fb86e27e2",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d00004851bac8015c7e47644fb86e27e2",
            width: 64,
          },
        ],
        name: "Things Fall Apart",
        release_date: "1999-02-23",
        release_date_precision: "day",
        total_tracks: 18,
        type: "album",
        uri: "spotify:album:0qbl8aNaCUOvX8HGsZYLfh",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/78xUyw6FkVZrRAtziFdtdu",
          },
          href: "https://api.spotify.com/v1/artists/78xUyw6FkVZrRAtziFdtdu",
          id: "78xUyw6FkVZrRAtziFdtdu",
          name: "The Roots",
          type: "artist",
          uri: "spotify:artist:78xUyw6FkVZrRAtziFdtdu",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/7i3os1iEWOn5UpaylRiMw5",
          },
          href: "https://api.spotify.com/v1/artists/7i3os1iEWOn5UpaylRiMw5",
          id: "7i3os1iEWOn5UpaylRiMw5",
          name: "Tariq Trotter",
          type: "artist",
          uri: "spotify:artist:7i3os1iEWOn5UpaylRiMw5",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/7IfculRW2WXyzNQ8djX8WX",
          },
          href: "https://api.spotify.com/v1/artists/7IfculRW2WXyzNQ8djX8WX",
          id: "7IfculRW2WXyzNQ8djX8WX",
          name: "Erykah Badu",
          type: "artist",
          uri: "spotify:artist:7IfculRW2WXyzNQ8djX8WX",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/4d3yvTptO48nOYTPBcPFZC",
          },
          href: "https://api.spotify.com/v1/artists/4d3yvTptO48nOYTPBcPFZC",
          id: "4d3yvTptO48nOYTPBcPFZC",
          name: "Eve",
          type: "artist",
          uri: "spotify:artist:4d3yvTptO48nOYTPBcPFZC",
        },
      ],
      available_markets: [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 259306,
      episode: false,
      explicit: true,
      external_ids: {
        isrc: "USMC19858697",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/4pdLZsxq0y5oJDb6Cxlokw",
      },
      href: "https://api.spotify.com/v1/tracks/4pdLZsxq0y5oJDb6Cxlokw",
      id: "4pdLZsxq0y5oJDb6Cxlokw",
      is_local: false,
      name: "You Got Me",
      popularity: 65,
      preview_url:
        "https://p.scdn.co/mp3-preview/162d28eee1d1e5195a2cb719cd3b7a25495a4580?cid=9cde7a664fdb40f78142817d91064645",
      track: true,
      track_number: 15,
      type: "track",
      uri: "spotify:track:4pdLZsxq0y5oJDb6Cxlokw",
    },
    video_thumbnail: {
      url: null,
    },
  },
  {
    added_at: "2020-02-25T20:31:38Z",
    added_by: {
      external_urls: {
        spotify: "https://open.spotify.com/user/",
      },
      href: "https://api.spotify.com/v1/users/",
      id: "",
      type: "user",
      uri: "spotify:user:",
    },
    is_local: false,
    primary_color: null,
    track: {
      album: {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7IfculRW2WXyzNQ8djX8WX",
            },
            href: "https://api.spotify.com/v1/artists/7IfculRW2WXyzNQ8djX8WX",
            id: "7IfculRW2WXyzNQ8djX8WX",
            name: "Erykah Badu",
            type: "artist",
            uri: "spotify:artist:7IfculRW2WXyzNQ8djX8WX",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3qr4pTBWEU1SVf01j6RAx3",
        },
        href: "https://api.spotify.com/v1/albums/3qr4pTBWEU1SVf01j6RAx3",
        id: "3qr4pTBWEU1SVf01j6RAx3",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b2739968770f3f0e45aa99b2ac29",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e029968770f3f0e45aa99b2ac29",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d000048519968770f3f0e45aa99b2ac29",
            width: 64,
          },
        ],
        name: "Baduizm",
        release_date: "1997-01-01",
        release_date_precision: "day",
        total_tracks: 14,
        type: "album",
        uri: "spotify:album:3qr4pTBWEU1SVf01j6RAx3",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/7IfculRW2WXyzNQ8djX8WX",
          },
          href: "https://api.spotify.com/v1/artists/7IfculRW2WXyzNQ8djX8WX",
          id: "7IfculRW2WXyzNQ8djX8WX",
          name: "Erykah Badu",
          type: "artist",
          uri: "spotify:artist:7IfculRW2WXyzNQ8djX8WX",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 226133,
      episode: false,
      explicit: true,
      external_ids: {
        isrc: "USUR19700556",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/0tNuJpBgtE65diL6Q8Q7fI",
      },
      href: "https://api.spotify.com/v1/tracks/0tNuJpBgtE65diL6Q8Q7fI",
      id: "0tNuJpBgtE65diL6Q8Q7fI",
      is_local: false,
      name: "On & On",
      popularity: 66,
      preview_url:
        "https://p.scdn.co/mp3-preview/fcd5dbe2bad3c8c6bacbedc2f54d13c8af40d877?cid=9cde7a664fdb40f78142817d91064645",
      track: true,
      track_number: 2,
      type: "track",
      uri: "spotify:track:0tNuJpBgtE65diL6Q8Q7fI",
    },
    video_thumbnail: {
      url: null,
    },
  },
  {
    added_at: "2020-02-25T20:31:38Z",
    added_by: {
      external_urls: {
        spotify: "https://open.spotify.com/user/",
      },
      href: "https://api.spotify.com/v1/users/",
      id: "",
      type: "user",
      uri: "spotify:user:",
    },
    is_local: false,
    primary_color: null,
    track: {
      album: {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5z2cHsOmmmWcAPNG1oEhw0",
            },
            href: "https://api.spotify.com/v1/artists/5z2cHsOmmmWcAPNG1oEhw0",
            id: "5z2cHsOmmmWcAPNG1oEhw0",
            name: "Xscape",
            type: "artist",
            uri: "spotify:artist:5z2cHsOmmmWcAPNG1oEhw0",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "BO",
          "BR",
          "CL",
          "CO",
          "CR",
          "DO",
          "EC",
          "GT",
          "HK",
          "HN",
          "ID",
          "IN",
          "MX",
          "MY",
          "NI",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PY",
          "SG",
          "SV",
          "TH",
          "TW",
          "US",
          "UY",
          "VN",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6lwTyWDtJbJ3czkIkUBPoj",
        },
        href: "https://api.spotify.com/v1/albums/6lwTyWDtJbJ3czkIkUBPoj",
        id: "6lwTyWDtJbJ3czkIkUBPoj",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b27311484556cede4a9eda744e4a",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e0211484556cede4a9eda744e4a",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d0000485111484556cede4a9eda744e4a",
            width: 64,
          },
        ],
        name: "Off The Hook",
        release_date: "1995-07-01",
        release_date_precision: "day",
        total_tracks: 12,
        type: "album",
        uri: "spotify:album:6lwTyWDtJbJ3czkIkUBPoj",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/5z2cHsOmmmWcAPNG1oEhw0",
          },
          href: "https://api.spotify.com/v1/artists/5z2cHsOmmmWcAPNG1oEhw0",
          id: "5z2cHsOmmmWcAPNG1oEhw0",
          name: "Xscape",
          type: "artist",
          uri: "spotify:artist:5z2cHsOmmmWcAPNG1oEhw0",
        },
      ],
      available_markets: [
        "AR",
        "AU",
        "BO",
        "BR",
        "CL",
        "CO",
        "CR",
        "DO",
        "EC",
        "GT",
        "HK",
        "HN",
        "ID",
        "IN",
        "MX",
        "MY",
        "NI",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PY",
        "SG",
        "SV",
        "TH",
        "TW",
        "US",
        "UY",
        "VN",
      ],
      disc_number: 1,
      duration_ms: 212040,
      episode: false,
      explicit: false,
      external_ids: {
        isrc: "USSM19500162",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/0b0vpt8e3AkV3GG8HoUEJm",
      },
      href: "https://api.spotify.com/v1/tracks/0b0vpt8e3AkV3GG8HoUEJm",
      id: "0b0vpt8e3AkV3GG8HoUEJm",
      is_local: false,
      name: "Feels So Good",
      popularity: 44,
      preview_url:
        "https://p.scdn.co/mp3-preview/748d2cfb4223853ba662e134c324ec0b49e5da59?cid=9cde7a664fdb40f78142817d91064645",
      track: true,
      track_number: 2,
      type: "track",
      uri: "spotify:track:0b0vpt8e3AkV3GG8HoUEJm",
    },
    video_thumbnail: {
      url: null,
    },
  },
  {
    added_at: "2020-02-25T20:31:38Z",
    added_by: {
      external_urls: {
        spotify: "https://open.spotify.com/user/",
      },
      href: "https://api.spotify.com/v1/users/",
      id: "",
      type: "user",
      uri: "spotify:user:",
    },
    is_local: false,
    primary_color: null,
    track: {
      album: {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/1XkoF8ryArs86LZvFOkbyr",
            },
            href: "https://api.spotify.com/v1/artists/1XkoF8ryArs86LZvFOkbyr",
            id: "1XkoF8ryArs86LZvFOkbyr",
            name: "Mary J. Blige",
            type: "artist",
            uri: "spotify:artist:1XkoF8ryArs86LZvFOkbyr",
          },
        ],
        available_markets: ["CA", "MX", "US"],
        external_urls: {
          spotify: "https://open.spotify.com/album/1OQ5l5rHKqUumPpn559zJC",
        },
        href: "https://api.spotify.com/v1/albums/1OQ5l5rHKqUumPpn559zJC",
        id: "1OQ5l5rHKqUumPpn559zJC",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b2730b283be60e1ca4d3b43137c2",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e020b283be60e1ca4d3b43137c2",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d000048510b283be60e1ca4d3b43137c2",
            width: 64,
          },
        ],
        name: "My Life",
        release_date: "1994-01-01",
        release_date_precision: "day",
        total_tracks: 17,
        type: "album",
        uri: "spotify:album:1OQ5l5rHKqUumPpn559zJC",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/1XkoF8ryArs86LZvFOkbyr",
          },
          href: "https://api.spotify.com/v1/artists/1XkoF8ryArs86LZvFOkbyr",
          id: "1XkoF8ryArs86LZvFOkbyr",
          name: "Mary J. Blige",
          type: "artist",
          uri: "spotify:artist:1XkoF8ryArs86LZvFOkbyr",
        },
      ],
      available_markets: ["CA", "MX", "US"],
      disc_number: 1,
      duration_ms: 349560,
      episode: false,
      explicit: false,
      external_ids: {
        isrc: "USMC19443788",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/5X82VFLvjpeWQlTSShqqj0",
      },
      href: "https://api.spotify.com/v1/tracks/5X82VFLvjpeWQlTSShqqj0",
      id: "5X82VFLvjpeWQlTSShqqj0",
      is_local: false,
      name: "Be Happy",
      popularity: 55,
      preview_url:
        "https://p.scdn.co/mp3-preview/a2d9da5b4edb331faad403cea48b0d918e0129c8?cid=9cde7a664fdb40f78142817d91064645",
      track: true,
      track_number: 17,
      type: "track",
      uri: "spotify:track:5X82VFLvjpeWQlTSShqqj0",
    },
    video_thumbnail: {
      url: null,
    },
  },
  {
    added_at: "2020-02-25T20:31:38Z",
    added_by: {
      external_urls: {
        spotify: "https://open.spotify.com/user/",
      },
      href: "https://api.spotify.com/v1/users/",
      id: "",
      type: "user",
      uri: "spotify:user:",
    },
    is_local: false,
    primary_color: null,
    track: {
      album: {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/1eNkUXHPaXyuyC8NAgzykK",
            },
            href: "https://api.spotify.com/v1/artists/1eNkUXHPaXyuyC8NAgzykK",
            id: "1eNkUXHPaXyuyC8NAgzykK",
            name: "Jodeci",
            type: "artist",
            uri: "spotify:artist:1eNkUXHPaXyuyC8NAgzykK",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/41pgxrq2gjdSsGnqofrHGj",
        },
        href: "https://api.spotify.com/v1/albums/41pgxrq2gjdSsGnqofrHGj",
        id: "41pgxrq2gjdSsGnqofrHGj",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b2733933a425e4cadd3dd7dda3a5",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e023933a425e4cadd3dd7dda3a5",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d000048513933a425e4cadd3dd7dda3a5",
            width: 64,
          },
        ],
        name: "Diary Of A Mad Band",
        release_date: "1993-12-21",
        release_date_precision: "day",
        total_tracks: 13,
        type: "album",
        uri: "spotify:album:41pgxrq2gjdSsGnqofrHGj",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/1eNkUXHPaXyuyC8NAgzykK",
          },
          href: "https://api.spotify.com/v1/artists/1eNkUXHPaXyuyC8NAgzykK",
          id: "1eNkUXHPaXyuyC8NAgzykK",
          name: "Jodeci",
          type: "artist",
          uri: "spotify:artist:1eNkUXHPaXyuyC8NAgzykK",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 300906,
      episode: false,
      explicit: false,
      external_ids: {
        isrc: "USMC19989292",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/3RNvMhYFEwpCgPnDGKR5MB",
      },
      href: "https://api.spotify.com/v1/tracks/3RNvMhYFEwpCgPnDGKR5MB",
      id: "3RNvMhYFEwpCgPnDGKR5MB",
      is_local: false,
      name: "Cry For You",
      popularity: 55,
      preview_url:
        "https://p.scdn.co/mp3-preview/8e607563c81969662e188fc79daaf8e12b30125b?cid=9cde7a664fdb40f78142817d91064645",
      track: true,
      track_number: 2,
      type: "track",
      uri: "spotify:track:3RNvMhYFEwpCgPnDGKR5MB",
    },
    video_thumbnail: {
      url: null,
    },
  },
];
